# Generated by Django 5.2.8 on 2026-04-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0002_brand_category_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendoraddress',
            table='store_admin_vendoraddress',
        ),
    ]
