# Generated by Django 5.2.12 on 2026-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0006_remove_vendoraddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='vendorbank',
            name='account_number',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Bank Account Number'),
        ),
    ]
