# Generated by Django 5.2.12 on 2026-04-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0007_alter_vendor_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payment_term',
            field=models.IntegerField(choices=[(1, 'Last date of next to next month (Forcetech)'), (2, 'Last date of next month (Bambury)'), (3, '14th of next month (Ingram)'), (4, 'Net 45 Days'), (5, 'Net 60 Days')], default=2),
        ),
    ]
