# Generated by Django 5.2.12 on 2026-04-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0008_alter_vendor_payment_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_country',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='reminder',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_model',
        ),
        migrations.RemoveField(
            model_name='vendorpaymentlog',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendorpaymentlogitem',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='vendorbank',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='vendorbank',
            name='bank_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorpaymentlog',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store_admin.vendor'),
        ),
        migrations.AddField(
            model_name='vendorpaymentlogitem',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store_admin.vendorpaymentlog'),
        ),
        migrations.AlterField(
            model_name='vendorbank',
            name='account_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
