# Generated by Django 5.2.12 on 2026-04-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0009_remove_vendor_account_name_and_more'),
    ]

    operations = [
    ]
