# Generated by Django 5.2.12 on 2026-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0011_update_shipping_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbank',
            name='account_number',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Bank Account Number'),
        ),
    ]
