# Generated by Django 5.2.12 on 2026-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0012_alter_vendorbank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='allow_negative_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='auto_detect_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
