# Generated by Django 5.2.12 on 2026-04-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0013_alter_vendor_allow_negative_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='allow_negative_balance',
            field=models.CharField(default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='auto_detect_invoice',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
