# Generated by Django 5.2.12 on 2026-04-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0014_alter_vendor_allow_negative_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraddress',
            name='suburb',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='state',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='post_code',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
    ]