# Generated by Django 5.2.8 on 2026-04-13 04:48

import django.db.models.deletion
import store_admin.models.vendor_models
from django.db import migrations, models


def seed_vendor_inventory_master_options(apps, schema_editor):
    Option = apps.get_model("store_admin", "VendorInventoryMasterOption")
    rows = [
        # inventory_frequency
        ("inventory_frequency", "daily", "Daily", 10),
        ("inventory_frequency", "weekly", "Weekly", 20),
        ("inventory_frequency", "biweekly", "Bi-weekly", 30),
        ("inventory_frequency", "monthly", "Monthly", 40),
        ("inventory_frequency", "quarterly", "Quarterly", 50),
        ("inventory_frequency", "on_request", "On Request", 60),
        ("inventory_frequency", "manual", "Manual", 70),
        # shared channel-style lists
        ("inventory_source", "email", "Email", 10),
        ("inventory_source", "ftp", "FTP", 20),
        ("inventory_source", "website", "Website", 30),
        ("inventory_source", "manual", "Manual", 40),
        ("inventory_source", "api", "API", 50),
        ("inventory_source", "edi", "EDI", 60),
        ("product_inventory_sync", "email", "Email", 10),
        ("product_inventory_sync", "ftp", "FTP", 20),
        ("product_inventory_sync", "website", "Website", 30),
        ("product_inventory_sync", "manual", "Manual", 40),
        ("product_inventory_sync", "api", "API", 50),
        ("product_inventory_sync", "realtime", "Real-time", 5),
        ("invoice_received_on", "email", "Email", 10),
        ("invoice_received_on", "ftp", "FTP", 20),
        ("invoice_received_on", "website", "Website", 30),
        ("invoice_received_on", "manual", "Manual", 40),
        ("invoice_received_on", "api", "API", 50),
        ("invoice_received_on", "portal", "Portal", 25),
        ("tracking_received_on", "email", "Email", 10),
        ("tracking_received_on", "ftp", "FTP", 20),
        ("tracking_received_on", "website", "Website", 30),
        ("tracking_received_on", "manual", "Manual", 40),
        ("tracking_received_on", "api", "API", 50),
        ("tracking_received_on", "carrier_feed", "Carrier Feed", 15),
        ("po_integration_type", "api", "API", 10),
        ("po_integration_type", "email", "Email", 20),
        ("po_integration_type", "ftp", "FTP", 30),
        ("po_integration_type", "website", "Website", 40),
        ("po_integration_type", "manual", "Manual", 50),
        ("po_integration_type", "edi", "EDI", 60),
    ]
    for list_type, code, label, sort_order in rows:
        Option.objects.get_or_create(
            list_type=list_type,
            code=code,
            defaults={"label": label, "sort_order": sort_order, "is_active": True},
        )


def unseed_vendor_inventory_master_options(apps, schema_editor):
    Inv = apps.get_model("store_admin", "VendorInventory")
    Option = apps.get_model("store_admin", "VendorInventoryMasterOption")
    Inv.objects.all().delete()
    Option.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("store_admin", "0020_repair_vendorbank_audit_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorInventoryMasterOption",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "list_type",
                    models.CharField(
                        choices=[
                            ("inventory_frequency", "Inventory Frequency"),
                            ("inventory_source", "Inventory Source"),
                            ("product_inventory_sync", "Product Inventory Sync"),
                            ("invoice_received_on", "Invoice Received On"),
                            ("tracking_received_on", "Tracking Received On"),
                            ("po_integration_type", "PO Integration Type"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("code", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_admin_vendor_inventory_master_option",
                "ordering": ["list_type", "sort_order", "label"],
                "unique_together": {("list_type", "code")},
            },
        ),
        migrations.CreateModel(
            name="VendorInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "integration_weblink",
                    models.CharField(
                        blank=True,
                        help_text="HTTPS/HTTP URL only; used for portal or feed links.",
                        max_length=500,
                        null=True,
                        validators=[store_admin.models.vendor_models.validate_https_http_url],
                    ),
                ),
                ("created_by", models.PositiveIntegerField(default=0)),
                ("updated_by", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_rows",
                        to="store_admin.vendor",
                    ),
                ),
                (
                    "inventory_frequency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
                (
                    "inventory_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
                (
                    "invoice_received_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
                (
                    "po_integration_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
                (
                    "product_inventory_sync",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
                (
                    "tracking_received_on",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="store_admin.vendorinventorymasteroption",
                    ),
                ),
            ],
            options={
                "db_table": "store_admin_vendor_inventory",
                "ordering": ["-id"],
            },
        ),
        migrations.RunPython(seed_vendor_inventory_master_options, unseed_vendor_inventory_master_options),
    ]
