# Generated by Django 5.2.12 on 2026-04-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0021_vendor_inventory_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payment_term',
            field=models.IntegerField(choices=[(1, 'Last day of Next to Next Month'), (2, 'Last day of Next Month'), (3, '14th of Next Month'), (4, 'Net 45 Days'), (5, 'Net 60 Days')], default=2),
        ),
        migrations.AlterModelTable(
            name='vendordocuments',
            table='store_admin_vendor_documents',
        ),
    ]
