# Generated by Django 5.2.12 on 2026-04-08 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0004_add_default_payment_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendoraddress',
            options={},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bank_verification_doc',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='default_warehouse',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='first_contact_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='first_contact_via',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='mode_of_contact',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='mode_of_payment',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='onboard_by',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='onboard_date',
        ),
        migrations.RemoveField(
            model_name='vendorbank',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendorcontact',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendordocuments',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendorwarehouse',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_locality',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vendorbank',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorbank',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='store_admin.vendor'),
        ),
        migrations.AddField(
            model_name='vendorcontact',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='store_admin.vendor'),
        ),
        migrations.AddField(
            model_name='vendordocuments',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='store_admin.vendor'),
        ),
        migrations.AddField(
            model_name='vendorwarehouse',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='store_admin.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_acc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_company_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vendorbank',
            name='account_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocuments',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vendorwarehouse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='vendordocuments',
            table=None,
        ),
    ]
