# Generated by Django 5.2.12 on 2026-04-08 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0005_alter_vendoraddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraddress',
            name='address',
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='created_by',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendoraddress',
            name='suburb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='address_type',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendoraddress',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store_admin.vendor'),
        ),
        migrations.AlterModelTable(
            name='vendoraddress',
            table=None,
        ),
    ]
